// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { useAuth } from '@clerk/clerk-react';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL!;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY!;

// Validação das variáveis de ambiente
if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    'Variáveis de ambiente do Supabase não configuradas. ' +
    'Verifique se VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY estão definidas no arquivo .env'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Cliente anônimo base (pode ser usado para operações públicas se houver)
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  global: {
    headers: {
      'X-Client-Info': 'imobipro-dashboard@1.0.0',
    },
  },
});

// Hook para obter um cliente Supabase autenticado dinamicamente
export function useSupabaseAuthenticatedClient() {
  const { getToken } = useAuth();

  // Retorna uma função que cria um cliente sob demanda com o token mais recente
  const createAuthenticatedClient = async () => {
    const token = await getToken({ template: 'supabase' });
    
    return createClient<Database>(supabaseUrl, supabaseAnonKey, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
          'X-Client-Info': 'imobipro-dashboard@1.0.0',
        }
      }
    });
  };

  return createAuthenticatedClient;
}

// Log de configuração para desenvolvimento (apenas em dev)
if (import.meta.env.DEV) {
  console.log('🔗 Supabase Client configurado com Clerk:', {
    url: supabaseUrl,
    project: 'ImobPRO',
    anon_key_prefix: supabaseAnonKey.substring(0, 20) + '...',
    auth_provider: 'Clerk JWT Template: supabase',
  });
}